DEFAULT_AI_MODEL = "Gemini 2.5 Flash"

AI_MODEL_OPTIONS = {
    "Gemini 2.5 Flash": {
        "provider": "gemini",
        "model": "gemini-2.5-flash",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "免費額度 / 收費",
        "selection_label": "日常練習",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$0.30 / 1M tokens（audio US$1.00 / 1M tokens），output US$2.50 / 1M tokens；Google Search 超額約 US$35 / 1,000 grounded prompts。",
        "input_price_per_million": 0.30,
        "audio_input_price_per_million": 1.00,
        "output_price_per_million": 2.50,
        "web_search_price_per_call": 0.035,
        "is_premium": False,
    },
    "Gemini 3.5 Flash": {
        "provider": "gemini",
        "model": "gemini-3.5-flash",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "免費額度 / 收費",
        "selection_label": "高質快速",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$1.50 / 1M tokens，output US$9.00 / 1M tokens；Google Search 超額約 US$14 / 1,000 search queries。",
        "input_price_per_million": 1.50,
        "audio_input_price_per_million": 1.50,
        "output_price_per_million": 9.00,
        "web_search_price_per_call": 0.014,
        "is_premium": False,
    },
    "Gemini 3.1 Pro": {
        "provider": "gemini",
        "model": "gemini-3.1-pro-preview",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "高級收費",
        "selection_label": "深入分析",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$2.00 / 1M tokens（prompt >200k：US$4.00），output US$12.00 / 1M tokens（prompt >200k：US$18.00）；Google Search 超額約 US$14 / 1,000 search queries。",
        "input_price_per_million": 2.00,
        "audio_input_price_per_million": 2.00,
        "output_price_per_million": 12.00,
        "web_search_price_per_call": 0.014,
        "is_premium": True,
    },
    "DeepSeek V4 Pro": {
        "provider": "openrouter",
        "model": "deepseek/deepseek-v4-pro",
        "api_key": "OPENROUTER_API_KEY",
        "supports_audio": False,
        "supports_web_search": True,
        "pricing_label": "收費",
        "selection_label": "平價推理",
        "pricing_note": "Provider: OpenRouter，支援上網搜尋，不支援錄音分析。",
        "paid_rate_note": "Input US$0.435 / 1M tokens，output US$0.87 / 1M tokens；OpenRouter fallback web search 約 US$0.005 / 次。",
        "input_price_per_million": 0.435,
        "audio_input_price_per_million": None,
        "output_price_per_million": 0.87,
        "web_search_price_per_call": 0.005,
        "is_premium": False,
    },
    "Haiku 4.5": {
        "provider": "openrouter",
        "model": "anthropic/claude-haiku-4.5",
        "api_key": "OPENROUTER_API_KEY",
        "supports_audio": False,
        "supports_web_search": True,
        "pricing_label": "收費",
        "selection_label": "第二意見",
        "pricing_note": "Provider: OpenRouter，支援上網搜尋，不支援錄音分析。",
        "paid_rate_note": "Input US$1.00 / 1M tokens，output US$5.00 / 1M tokens；OpenRouter web search 約 US$0.01 / 次。",
        "input_price_per_million": 1.00,
        "audio_input_price_per_million": None,
        "output_price_per_million": 5.00,
        "web_search_price_per_call": 0.01,
        "is_premium": True,
    },
    "GPT-5.4 Mini": {
        "provider": "openrouter",
        "model": "openai/gpt-5.4-mini",
        "api_key": "OPENROUTER_API_KEY",
        "supports_audio": False,
        "supports_web_search": True,
        "pricing_label": "收費",
        "selection_label": "重要先用",
        "pricing_note": "Provider: OpenRouter，支援上網搜尋，不支援錄音分析。",
        "paid_rate_note": "Input US$0.75 / 1M tokens，output US$4.50 / 1M tokens；OpenRouter web search 約 US$0.01 / 次。",
        "input_price_per_million": 0.75,
        "audio_input_price_per_million": None,
        "output_price_per_million": 4.50,
        "web_search_price_per_call": 0.01,
        "is_premium": True,
    },
}

NON_MANUAL_DEFAULT_AI_MODEL = "Gemini 3.5 Flash"

NON_MANUAL_MODEL_OPTIONS = {
    "Gemini 3.5 Flash": {
        "provider": "gemini",
        "model": "gemini-3.5-flash",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "免費額度 / 收費",
        "selection_label": "預設高質",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$1.50 / 1M tokens，output US$9.00 / 1M tokens；Google Search 超額約 US$14 / 1,000 search queries。",
        "input_price_per_million": 1.50,
        "audio_input_price_per_million": 1.50,
        "output_price_per_million": 9.00,
        "web_search_price_per_call": 0.014,
        "is_premium": False,
    },
    "Gemini 2.5 Flash": {
        "provider": "gemini",
        "model": "gemini-2.5-flash",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "免費額度 / 收費",
        "selection_label": "日常練習",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$0.30 / 1M tokens（audio US$1.00 / 1M tokens），output US$2.50 / 1M tokens；Google Search 超額約 US$35 / 1,000 grounded prompts。",
        "input_price_per_million": 0.30,
        "audio_input_price_per_million": 1.00,
        "output_price_per_million": 2.50,
        "web_search_price_per_call": 0.035,
        "is_premium": False,
    },
    "Gemini 2.5 Flash Lite": {
        "provider": "gemini",
        "model": "gemini-2.5-flash-lite",
        "api_key": "GEMINI_API_KEY",
        "supports_audio": True,
        "supports_web_search": True,
        "pricing_label": "免費額度 / 收費",
        "selection_label": "慳錢快速",
        "pricing_note": "Provider: Google AI Studio，支援上網搜尋及錄音分析。",
        "paid_rate_note": "Input US$0.10 / 1M tokens，output US$0.40 / 1M tokens；Google Search 費用按 Google AI Studio 實際帳單為準。",
        "input_price_per_million": 0.10,
        "audio_input_price_per_million": 0.10,
        "output_price_per_million": 0.40,
        "web_search_price_per_call": 0.035,
        "is_premium": False,
    },
}

ROOM_JUDGEMENT_MODEL_LABELS = (
    "Gemini 3.5 Flash",
    "Gemini 2.5 Flash",
    "Gemini 2.5 Flash Lite",
)


def model_slugs_for_labels(labels):
    return tuple(
        NON_MANUAL_MODEL_OPTIONS[label]["model"]
        for label in labels
        if label in NON_MANUAL_MODEL_OPTIONS
    )
