/* Small parity adapters shared by the direct-HTML AI workspaces. */
(() => {
  const download = (name, text) => {
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([text], {type: "text/markdown;charset=utf-8"}));
    link.download = name; link.click(); setTimeout(() => URL.revokeObjectURL(link.href), 1000);
  };
  if (location.pathname === "/ai-coach") {
    [["strategyResult","主線策劃"],["researchResult","搵料結果"],["factResult","Fact-Check結果"]].forEach(([id,name]) => {
      const result = document.getElementById(id); if (!result) return;
      const button = document.createElement("button"); button.type="button"; button.textContent="下載 Markdown"; button.className="hidden";
      result.after(button); button.onclick=()=>download(`${name}.md`, result.textContent);
      new MutationObserver(()=>button.classList.toggle("hidden", !result.textContent || /填寫|保留可核查|輸入一項/.test(result.textContent))).observe(result,{childList:true,characterData:true,subtree:true});
    });
    const $=id=>document.getElementById(id);let meta=null;
    const request=async(url,opt={})=>{const r=await fetch(url,{credentials:"same-origin",headers:{"Content-Type":"application/json"},...opt}),d=await r.json();if(!r.ok)throw Error(d.detail||"操作失敗");return d};
    const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
    function source(formId,topicId){const form=$(formId),topic=$(topicId);if(!form||!topic)return;const box=document.createElement("div");box.innerHTML='<label>辯題來源<select><option>手動輸入</option><option>從辯題庫選擇</option><option>從系統場次載入</option></select></label><label class="hidden">選擇辯題<select></select></label><p class="caption"></p>';form.insertBefore(box,topic.closest("label"));const mode=box.querySelector("select"),wrap=box.querySelectorAll("label")[1],pick=wrap.querySelector("select"),note=box.querySelector("p");mode.onchange=()=>{const manual=mode.value==="手動輸入",rows=mode.value==="從系統場次載入"?meta.matches:meta.topics;wrap.classList.toggle("hidden",manual);topic.closest("label").classList.toggle("hidden",!manual);pick.innerHTML=rows.map((r,i)=>`<option value="${i}">${esc(mode.value==="從系統場次載入"?`${r.match_id}｜${r.topic_text||"未設定"}`:`[${r.category||"未分類"}｜${r.difficulty||"未標示"}] ${r.topic_text}`)}</option>`).join("");pick.onchange=()=>{const r=rows[+pick.value];if(r){topic.value=r.topic_text||"";note.textContent=mode.value==="從系統場次載入"?`正方：${r.pro_team||"—"}｜反方：${r.con_team||"—"}`:`類別：${r.category||"—"}｜難度：${r.difficulty||"—"}`}};pick.onchange()};mode.onchange()}
    function reviewExtras(){const field=$("reviewText").closest("label"),box=document.createElement("div");box.innerHTML='<div class="room-grid"><label>賽制<select id="reviewFormat"><option>校園隨想</option><option>基本法盃</option><option>聯中</option><option>星島</option></select></label><label>練習類型<select id="reviewMode"><option>台上發言</option><option>台下發問</option><option>交互答問</option></select></label></div><div id="qaFields" class="hidden"><label>AI／對方問題<textarea id="qaQuestion" rows="3" placeholder="可留空，AI 會先問"></textarea></label><label>我嘅回答／追問<textarea id="qaAnswer" rows="4"></textarea></label></div><div class="rec"><button id="speechTimer" type="button">開始計時</button><span id="speechClock">00:00.000</span></div>';field.before(box);$("reviewMode").onchange=()=>$("qaFields").classList.toggle("hidden",$("reviewMode").value==="台上發言");let timer,start;$("speechTimer").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("speechTimer").textContent="開始計時";return}start=performance.now();$("speechTimer").textContent="暫停計時";timer=setInterval(()=>{const ms=performance.now()-start;$("speechClock").textContent=`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms/1000)%60).padStart(2,"0")}.${String(Math.floor(ms%1000)).padStart(3,"0")}`},31)};$("reviewForm").addEventListener("submit",()=>{if($("reviewMode").value!=="台上發言")$("reviewText").value=`## ${$("reviewMode").value}練習\nAI／對方問題：${$("qaQuestion").value}\n我嘅回答／追問：${$("qaAnswer").value}`},true)}
    async function prepare(mode,topic,side,format,minutes){const d=await request("/api/ai-coach/prepare-live",{method:"POST",body:JSON.stringify({topic,side,debate_format:format,mode,model_label:$("globalModel").value})});location.href="/practice/ai-debate/live?"+new URLSearchParams({mode,topic,side,format,minutes,brief_id:d.brief_id})}
    async function enhance(){meta=await request("/api/ai-coach/data");$("globalModel").innerHTML=meta.models.map(m=>`<option ${m.label===meta.default_model?"selected":""}>${esc(m.label)}</option>`).join("");const sync=()=>{const m=meta.models.find(x=>x.label===$("globalModel").value);document.querySelectorAll(".model").forEach(x=>{x.value=m.label;x.closest("label").classList.add("hidden")});$("modelNote").textContent=`${m.pricing_label||""}｜${m.note||""}`;const warnings=[];if(m.is_premium)warnings.push("你正在使用高級模型，請避免濫用。");if(!m.available)warnings.push(`未設定 ${m.api_key_name}，此模型暫時不能使用。`);if(meta.fund.balance_hkd<meta.fund.low_balance_hkd)warnings.push(`AI基金餘額偏低：HKD ${meta.fund.balance_hkd.toFixed(2)}。`);if(!m.supports_audio)warnings.push("此模型不支援錄音分析。");$("modelWarnings").innerHTML=warnings.map(x=>`<div class="notice warn">⚠️ ${esc(x)}</div>`).join("")};$("globalModel").onchange=sync;sync();[["strategyForm","strategyTopic"],["reviewForm","reviewTopic"],["researchForm","researchTopic"],["liveForm","liveTopic"],["mockForm","mockTopic"]].forEach(x=>source(...x));reviewExtras();const result=$("reviewResult"),button=document.createElement("button");button.type="button";button.textContent="下載 Markdown";button.className="hidden";result.after(button);button.onclick=()=>download("發言評語.md",result.textContent);new MutationObserver(()=>button.classList.toggle("hidden",/錄音或貼上/.test(result.textContent))).observe(result,{childList:true,subtree:true});$("liveForm").onsubmit=e=>{e.preventDefault();prepare("free",$("liveTopic").value,$("liveSide").value,$("liveFormat").value,$("liveMinutes").value).catch(e=>VoteUI.toast($("toast"),"⚠️ "+e.message))};$("mockFormat").onchange=()=>$("mockMinutesWrap").classList.toggle("hidden",$("mockFormat").value!=="聯中");$("mockForm").onsubmit=e=>{e.preventDefault();prepare("mock",$("mockTopic").value,$("mockSide").value,$("mockFormat").value,$("mockMinutes").value).catch(e=>VoteUI.toast($("toast"),"⚠️ "+e.message))}}
    const ready=new MutationObserver(()=>{if(!$("app").classList.contains("hidden")&&!meta){ready.disconnect();enhance().catch(()=>{})}});ready.observe($("app"),{attributes:true,attributeFilter:["class"]});
    const costs=()=>{if(!meta)return;const m=meta.models.find(x=>x.label===$("globalModel").value);if(!m?.estimates)return;const base=`${m.pricing_label||""}｜${m.note||""}`;$("modelNote").textContent=`${base}｜估算：主線 HKD ${m.estimates.strategy.hkd.toFixed(4)}、發言分析 HKD ${m.estimates.speech_review.hkd.toFixed(4)}、搜尋 HKD ${m.estimates.web_research.hkd.toFixed(4)}／次。`};
    $("globalModel").addEventListener("change",()=>setTimeout(costs));new MutationObserver(()=>setTimeout(costs)).observe($("app"),{attributes:true,attributeFilter:["class"]});
    function exactTimer(){if(!meta||!$("speechTimer")||$("speechTimer").dataset.exact)return;$("speechTimer").dataset.exact="1";const label=document.createElement("label");label.innerHTML='計時環節<select id="reviewStage"></select>';$("speechTimer").parentElement.before(label);const populate=()=>{$("reviewStage").innerHTML=(meta.formats[$("reviewFormat").value]?.timer_stages||[]).map(([key,name])=>`<option value="${key}">${esc(name)}</option>`).join("")};$("reviewFormat").addEventListener("change",populate);populate();let timer=null,start=0,fired=new Set();const ring=count=>{const ctx=new(window.AudioContext||window.webkitAudioContext)();for(let i=0;i<count;i++){const osc=ctx.createOscillator(),gain=ctx.createGain(),at=ctx.currentTime+i*.2;osc.frequency.value=880;gain.gain.setValueAtTime(.18,at);gain.gain.exponentialRampToValueAtTime(.001,at+.13);osc.connect(gain).connect(ctx.destination);osc.start(at);osc.stop(at+.14)}};$("speechTimer").onclick=()=>{if(timer){clearInterval(timer);timer=null;$("speechTimer").textContent="開始計時";return}start=performance.now();fired=new Set();$("speechTimer").textContent="暫停計時";const tick=()=>{const config=meta.formats[$("reviewFormat").value],stage=$("reviewStage").value,schedule=config.bell_schedules[stage]||[],elapsed=(performance.now()-start)/1000,end=config.overtime_times[stage]??schedule.at(-1)?.t??0,remaining=end-elapsed,abs=Math.abs(remaining),m=Math.floor(abs/60),s=Math.floor(abs)%60,ms=Math.floor(abs%1*1000);$("speechClock").textContent=`${remaining<0?"-":""}${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}.${String(ms).padStart(3,"0")}`;schedule.forEach((bell,index)=>{if(elapsed>=bell.t&&!fired.has(index)){fired.add(index);ring(bell.rings)}})};tick();timer=setInterval(tick,31)}}
    new MutationObserver(()=>setTimeout(exactTimer)).observe($("app"),{attributes:true,attributeFilter:["class"]});
    const parityPoll=setInterval(()=>{if(meta&&$("speechTimer")){costs();exactTimer();clearInterval(parityPoll)}},100);
  }
})();
